<?php

namespace App\Controller;

use App\Form\ContactType;
use Swift_Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class ContactController extends AbstractController
{
    /**
     * @Route("/kontakti", name="kontakti")
     * @param Request $request
     * @param Swift_Mailer $mailer
     * @param ParameterBagInterface $params
     * @return RedirectResponse|Response
     */
    public function kontakti(Request $request, Swift_Mailer $mailer, ParameterBagInterface $params)
    {
        $form = $this->createForm(ContactType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactFormData = $form->getData();

            $transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
                ->setUsername('7e5d04c7754c2f') // generated by Mailtrap
                ->setPassword('a3a6c86a2de6e9') // generated by Mailtrap
            ;
            $mailer = new Swift_Mailer($transport);

            $message = (new \Swift_Message('Jūs esat saņemis vēstuli!'))
                ->setFrom($contactFormData["email"], $contactFormData['name'] )
                ->setTo("deju.guru.info@gmail.com")
                ->setBody($contactFormData['message'], 'text/plain');

            $mailer->send($message);

            $this->addFlash('success', 'Veiksmīgi ir aizsutīta ziņa.');
            return $this->redirectToRoute('kontakti');
        }

        return $this->render('contact/contacts.html.twig', [
            'our_form' => $form->createView()
        ]);
    }
}
